#!/usr/bin/env bash
set -euo pipefail

# ── Inputs (set by action.yml as env vars) ──────────────────────────────────
SOURCE_REPO="${INPUT_SOURCE_REPO:?source-repo is required}"
SOURCE_REF="${INPUT_SOURCE_REF:?source-ref is required}"
SOURCE_PATH="${INPUT_SOURCE_PATH:?source-path is required}"
TARGET_PATH="${INPUT_TARGET_PATH:?target-path is required}"
PR_TITLE="${INPUT_PR_TITLE:?pr-title is required}"
BRANCH_NAME="${INPUT_BRANCH_NAME:?branch-name is required}"
TARGET_BRANCH="${INPUT_TARGET_BRANCH:-}"
PR_LABELS="${INPUT_PR_LABELS:-}"

# ── 1. Fetch the canonical file ─────────────────────────────────────────────
REMOTE_URL="https://raw.githubusercontent.com/${SOURCE_REPO}/${SOURCE_REF}/${SOURCE_PATH}"
echo "Fetching ${REMOTE_URL}"

TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT

HTTP_CODE=$(curl -sL -w "%{http_code}" -o "$TMPFILE" "$REMOTE_URL")
if [[ "$HTTP_CODE" != "200" ]]; then
  echo "::error::Failed to fetch source file (HTTP ${HTTP_CODE}): ${REMOTE_URL}"
  exit 1
fi

# ── 2. Compare with local copy ──────────────────────────────────────────────
if [[ -f "$TARGET_PATH" ]] && diff -q "$TMPFILE" "$TARGET_PATH" > /dev/null 2>&1; then
  echo "Local ${TARGET_PATH} is already up to date. Nothing to do."
  exit 0
fi

echo "Drift detected — will open or update a sync PR."

# ── 3. Determine the target branch ──────────────────────────────────────────
if [[ -n "$TARGET_BRANCH" ]]; then
  echo "Using supplied target branch: ${TARGET_BRANCH}"
else
  TARGET_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's|refs/remotes/origin/||' || true)
  if [[ -z "$TARGET_BRANCH" ]]; then
    TARGET_BRANCH=$(gh repo view --json defaultBranchRef -q '.defaultBranchRef.name')
  fi
  echo "Auto-detected target branch: ${TARGET_BRANCH}"
fi

# ── 4. Check for an existing open PR from this branch ───────────────────────
EXISTING_PR=$(gh pr list --head "$BRANCH_NAME" --state open --json number -q '.[0].number' || true)

# ── 5. Create / update the sync branch ──────────────────────────────────────
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

git fetch origin "$TARGET_BRANCH"
git checkout -B "$BRANCH_NAME" "origin/${TARGET_BRANCH}"

# Ensure target directory exists
TARGET_DIR=$(dirname "$TARGET_PATH")
if [[ "$TARGET_DIR" != "." ]]; then
  mkdir -p "$TARGET_DIR"
fi

cp "$TMPFILE" "$TARGET_PATH"
git add "$TARGET_PATH"

if git diff --cached --quiet; then
  echo "No effective changes after staging. Nothing to do."
  exit 0
fi

git commit -m "${PR_TITLE}

Synced from ${SOURCE_REPO}@${SOURCE_REF}:${SOURCE_PATH}"

# ── 6. Force-push the branch ────────────────────────────────────────────────
git push --force origin "$BRANCH_NAME"

# ── 7. Open or update the PR ────────────────────────────────────────────────
PR_BODY="This PR syncs \`${TARGET_PATH}\` from the canonical source at [\`${SOURCE_REPO}@${SOURCE_REF}\`](https://github.com/${SOURCE_REPO}/tree/${SOURCE_REF}/${SOURCE_PATH}).

> Auto-generated by [claude-md-sync](https://github.com/${SOURCE_REPO})."

if [[ -n "$EXISTING_PR" ]]; then
  echo "Updating existing PR #${EXISTING_PR}"
  gh pr comment "$EXISTING_PR" --body "Refreshed — branch force-pushed with latest upstream changes."
else
  echo "Creating new PR"
  LABEL_ARGS=()
  if [[ -n "$PR_LABELS" ]]; then
    IFS=',' read -ra LABELS <<< "$PR_LABELS"
    for label in "${LABELS[@]}"; do
      trimmed=$(echo "$label" | xargs)
      if [[ -n "$trimmed" ]]; then
        gh label create "$trimmed" --force 2>/dev/null || true
        LABEL_ARGS+=(--label "$trimmed")
      fi
    done
  fi

  gh pr create \
    --title "$PR_TITLE" \
    --body "$PR_BODY" \
    --head "$BRANCH_NAME" \
    --base "$TARGET_BRANCH" \
    "${LABEL_ARGS[@]+"${LABEL_ARGS[@]}"}"
fi

echo "Done."
